### ISSUE TITLE
Multiple "onUrl" and "offUrl" with "stateful" switches

### ISSUE THREAD

**Issue by 420Dope** [Supereg/homebridge-http-switch#15] opened 2018-09-25 19:21 UTC
Can you add multiple "onUrl" and "offUrl" with "stateful" switches?
When i use this
```
        {
			"accessory": "HTTP-SWITCH",
			"name": "Test",
			"switchType": "stateful",
			"onUrl": [
			"http://localhost/api/switch1On",
			"http://localhost/api/switch2On"
			],
			"offUrl": [
			"http://localhost/api/switch1Off",
			"http://localhost/api/switch2Off"
			],
			"statusUrl": "http://localhost/api/powerstate",
			"pullInterval": "10000",
			"statusPattern": "false",
			"auth": {
			"username": "user",
			"password": "pass"
			  }
        }
```
homebridge starts with this error
```
[2018-9-25 21:00:07] [TV Schlafzimmer] Error occurred while parsing 'onUrl': property cannot be an array!
[2018-9-25 21:00:07] [TV Schlafzimmer] Aborting...
```

When i use this
```
        {
			"accessory": "HTTP-SWITCH",
			"name": "Test",
			"switchType": "stateful",
			"onUrl": [
			{
			"url": "http://localhost/api/switch1On"
			},
			{
			"url": "http://localhost/api/switch2On"
			}
			],
			"offUrl": [
			{
			"url": "http://localhost/api/switch1Off"
			},
			{
			"url": "http://localhost/api/switch2Off"
			}
			],
			"statusUrl": "http://localhost/api/powerstate",
			"pullInterval": "10000",
			"statusPattern": "false",
			"auth": {
			"username": "user",
			"password": "pass"
			  }
        }
```
homebridge crashes on start.
Would be nice if you can add this festure.

**Comment by Supereg** [comment] 2018-09-27 16:09
I actively chose to not support that. I don't think that would be good design since there would be multiple urls called when the switch is switched on/off but the actual status can only be received from one url. Would be a nicer way working with HomeKit automations to trigger a separate switch when the switch is activated.
What exact use case are you thinking about?

Could you paste the log when Homebridge crashes? Cause I can't reproduce this and as I double checked in the code this particular config cannot be the cause for a crash.

**Comment by 420Dope** [comment] 2018-09-27 16:44
Ah ok...
I would use it for my TV, receiver, music amplifier. In the power plug (with Tasmota) is the TV and the music amplifier. My receiver is in a plug which have always power because it must always be in standby vor recodring and other things.
So now, i must 1. say to siri, turn on the power plug and 2. turn on my receiver. When i can use multiple urls, i can just say turn on my TV and the power plug and the receiver turns on.

I can´t paste a log when homebridge crashes, because i have it installs on windows and can´t find a way to save the log in a file. When it crashes the command prompt closes directly.
I have search the web and have find other windows users with the same problem and nobody have a solution to save the log. So honestly i am sorry...

**Comment by Supereg** [comment] 2018-09-27 16:58
Wouldn't it be easier to create a switch for every device (one for TV and one for the receiver) so you are able to control both devices individually and then but those two switches into a scene called for example "TV Time" and the call Siri with "Hey Siri, TV Time"? 😅 Or just record a own phrase with Siri Shortcuts and iOS 12 for this particular scene.
Or you create an automation that when the TV is turning on the receiver should also turn on (or also off). Only problem maybe is that you need some sort of HomeKit Hub (Apple TV, iPad, HomePod).

In my opinion this is much better design cause you don't lose the functionality of having control of both devices separately. And automations and scenes are designed for this exact scenario, to control a  devices in bulk with one command.

Would this work for you? Otherwise I could think about unofficially support this kind of setup.

How do you start homebridge? By command or some .bat scripts? I'm not really working with Windows anymore. Maybe this could help you https://helpdeskgeek.com/how-to/redirect-output-from-command-line-to-text-file/.

**Comment by 420Dope** [comment] 2018-09-27 18:45
Ahhhh haha, i doesnˋt know scenes. I only know the automation. I have a switch for every device and with automation i donˋt can controll the devices individually, thats why i have ask for the mutiple urls. Now with scenes it works how i want. Thank you very much and sorry for the ignorance, i am new with homebridge and homekit ;)

Thats a good hint, tomorrow i will look if i become a logfile with this if the command prompt closes directly on start when i use multiple urls. Thanks again (:

**Comment by Supereg** [comment] 2018-09-27 20:18
Everything's alright 😄
I will close this issue for now, but you can come back if you have any more information about the crash.

**Closed by Supereg** 2018-09-27 20:18 UTC
