### ISSUE TITLE
Support for HTTP POST and 'data' / 'form' elements in the post

### ISSUE THREAD

**Issue by roncoejr** [Supereg/homebridge-http-switch#27] opened 2018-12-31 23:03 UTC
**Is your feature request related to a problem? Please describe.**
While the documentation for the solution indicates that GET is the default configuration parameter for ObjUrl, it does indeed appear that it is the only option at this time.  I had my ObjUrl configured for POST commands and can confirm that each of the POST (from a network packet capture standpoint) were empty.  I'm not sure if this is a problem with the plugin itself, homebridge, or HomeKit.

**Describe the solution you'd like**
I'd like to be able to use ObjUrl parameters that are both configured for POST and that use the 'data' element of the POST as well as the 'form' element.  I would like to be able to choose which parts of the POST content to use.

**Comment by Supereg** [comment] 2019-01-02 19:17
I'm not exactly sure that you read the README/manual. When using POST you need of course specify the `body` property in the urlObject.
If you want to send data as 'form' you need to properly specify the header `Content-type: application/x-www-form-urlencoded` and specify the `body` as required (`variableOne=valueOne&variableTwo=valueTwo`)

I'm not sure what you expect me to add? Did I misunderstand anything?

**Comment by roncoejr** [comment] 2019-01-02 20:00
Thank you for the feedback. I can assure you that I have read the README—more than a couple of times. In fact, it is because of that document that my solution is now working. Albeit with GET requests.  Perhaps there is some nuance to the component that I have developed that is the root cause, but for me using POST requests with this plugin results in an empty HTTP payload on the wire—as the Wireshark image that I posted illustrates.

**Comment by Supereg** [comment] 2019-01-02 20:33
I remebered using POST request successfully with this plugin. After that I’m not so sure anymore. 
I will try to reproduce that in my end tomorrow. Maybe I totally confused something on my side. 

And sorry, my response shouldn’t sound do offending 😅

**Comment by Supereg** [comment] 2019-01-19 12:43
Okay, so today I got time to try to reproduce your issue finding that for me POST requests working perfectly fine. I even captured it with Wireshark as well.
What configuration do you exactly use to get this issue?

<img width="664" alt="bildschirmfoto 2019-01-19 um 13 41 51" src="https://user-images.githubusercontent.com/9783857/51426801-10d4e700-1bf0-11e9-874a-ea80b34777b0.png">

**Comment by Supereg** [comment] 2019-02-08 14:09
Closing this for now, since POST works as shown an no answer is coming from your side.
Feel free to reopen the issue if you got new information.

**Closed by Supereg** 2019-02-08 14:09 UTC
