### ISSUE TITLE
Adding accessory types.

### ISSUE THREAD

**Issue by whreams** [Supereg/homebridge-http-switch#66] opened 2020-07-25 20:12 UTC
Feature Request:

In order to use the "switch" as an enabler of different accessory types, can the switch be configured to allow for the available types of accessories listed in HomeKit?  Being able to list the available accessories in HomeKit and assign the appropriate "icon" for the accessory would allow for the "less I/T say" users in the home to see what the said "button" is to be used for. 

Example:
Switch for: Music
Switch for: Fan
Switch for: etc...

**Comment by Supereg** [comment] 2023-02-16 13:57
duplicate of #107. closing in favour of this

**Closed by Supereg** 2023-02-16 13:57 UTC
